name: vet_connect
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio:
  file_picker:
  intl:
  path_provider:
  equatable:
  remixicon:
  flutter_screenutil:
  flutter_spinkit:
  connectivity_plus:
  cached_network_image:
  flutter_launcher_icons:
  chatview:
  timeago:
  shared_preferences:
  flutter_svg:
  transparent_image:
  helpers:
  socket_io_client:
  chat_bubbles:
  permission_handler:
  go_router:
  flutter_riverpod:
  animated_switcher_plus:
  flex_color_scheme:
  flutter_staggered_animations:
  skeletonizer:
  fluttertoast:
  url_launcher:
  flutter_otp_text_field:
  dropdown_button2:
  badges:
  photo_view:
  animated_text_kit:
  web_socket_channel:
  awesome_notifications:
  jiffy:
  rxdart:
  google_maps_flutter:
  google_maps_flutter_web:
  table_calendar:
  firebase_core: ^2.24.2 
  location:
  google_maps_flutter_android:
  google_maps_flutter_platform_interface:
  cloud_firestore:
  firebase_auth:
  firebase_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  image_path_android: "assets/logo.png"
  image_path_ios: "assets/logo.png"
  android: true
  ios: true
  adaptive_icon_background: "#F5F5F5"
  adaptive_icon_foreground: "assets/logo.png"
  min_sdk_android: 29
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Catamaran
      fonts:
        - asset: fonts/Catamaran-Black.ttf
        - asset: fonts/Catamaran-Bold.ttf
        - asset: fonts/Catamaran-Light.ttf
        - asset: fonts/Catamaran-Regular.ttf
        - asset: fonts/Catamaran-Medium.ttf
        - asset: fonts/Catamaran-SemiBold.ttf
        - asset: fonts/Catamaran-Thin.ttf

    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Black.ttf
        - asset: fonts/NotoSans-Bold.ttf
        - asset: fonts/NotoSans-Light.ttf
        - asset: fonts/NotoSans-Regular.ttf
        - asset: fonts/NotoSans-Medium.ttf
        - asset: fonts/NotoSans-SemiBold.ttf
        - asset: fonts/NotoSans-Thin.ttf
